package com.example.cleanarchmvvm;

import android.app.Application;
import android.os.AsyncTask;

import androidx.lifecycle.LiveData;

import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;


// Repository is just a normal java class not directly related to the room library
// it is the one that is actually responsible for crud operations for the database.
// and it should be the one responsible for communicating with data sources.
// even with apis.

public class AppRepository {
    private NoteDao noteDao;
    private LiveData<List<Note>> allNotes;
    private Executor executor = Executors.newSingleThreadExecutor();

    public AppRepository(Application application) {
        AppDatabase database = AppDatabase.getInstance(application);
        noteDao = database.noteDao(); // generated by room
        allNotes = noteDao.getAllNotes(); // also generated by room, shouldn't this be async task too?
    }


    public void insert(Note note) {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                noteDao.insert(note);
            }
        });
    }

    public void update(Note note) {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                noteDao.update(note);
            }
        });
    }

    public void delete(Note note) {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                noteDao.delete(note);
            }
        });
    }

    public void deleteAllNotes() {
        executor.execute(new Runnable() {
            @Override
            public void run() {
                noteDao.deleteAllNotes();
            }
        });
    }

    public LiveData<List<Note>> getAllNotes() {
        return allNotes;
    }

}
